const ADD_CARD_DECK = "ADD_CARD_DECK";
const REMOVE_CARD_DECK = "REMOVE_CARD_DECK";
const ADD_CARD_HAND = "ADD_CARD_HAND";
const REMOVE_CARD_HAND = "REMOVE_CARD_HAND";
const FETCH_DECK = "FETCH_DECK";
const FETCH_DECK_SUCCESS = "FETCH_DECK_SUCCESS"
const FETCH_DECK_FAILURE = "FETCH_DECK_FAILURE"


export default {
    ADD_CARD_DECK,
    REMOVE_CARD_DECK,
    FETCH_DECK,
    ADD_CARD_HAND,
    REMOVE_CARD_HAND,
    FETCH_DECK_SUCCESS,
    FETCH_DECK_FAILURE
};
